# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-dz9M8R5-2TyFnWRo2pX87Qpuwegs69
"""

import pandas as pd

train=pd.read_csv('/content/train.csv') #upload the path of the train.csv dataset

train.head() #first five values of the dataset

train.describe()

train.shape

"""**DATA CLEANING**"""

train.info()

train.isnull().sum()

train.drop(['Cabin'],axis=1,inplace=True) #dropping the cabin as it has many null values

train['Age'].fillna(train['Age'].mean(),inplace=True)

train['Embarked'].value_counts()

train['Embarked'].fillna("S",inplace=True)

train.isnull().sum()

"""**DATA ANALYSIS**"""

train.describe()

import seaborn as sns

train['Survived'].value_counts()

sns.countplot(x='Sex',hue='Survived',data=train)

sns.countplot(x='Pclass',hue='Survived',data=train)

train.replace({"Sex":{"male":0,"female":1}},inplace=True)
train.replace({"Embarked":{"S":0,"C":1,"Q":2}},inplace=True)

train.head()

X = train.drop(["PassengerId","Survived","Name","Ticket"],axis=1)
Y = train["Survived"]

X
X.shape

Y
Y.shape

from sklearn.model_selection import train_test_split as tts

x_train,x_test,y_train,y_test = tts(X,Y,test_size=0.2,random_state=42)

print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(x_train,y_train)

"""**MODEL EVALUATION**"""

from sklearn.metrics import accuracy_score

x_train_prediction=model.predict(x_train)
x_train_prediction

accuracy_train=accuracy_score(y_train,x_train_prediction)

accuracy_train

x_test_prediction=model.predict(x_test)
x_test_prediction

accuracy_test=accuracy_score(y_test,x_test_prediction)
accuracy_test

import pickle

with open("model.pkl","wb") as f:
  pickle.dump(model,f)

with open("model.pkl","rb") as f:
  loaded_model=pickle.load(f)

!pip install streamlit

import streamlit as st

import streamlit as st
import math
import pickle

with open("model.pkl",'rb') as f:
    model = pickle.load(f)

st.header("Titanic Survival Prediction !!")

col1, col2,col3 = st.columns(3)
with col1:
    Pclass = st.selectbox("Class of Passenger",("Premiere","Executive","Economy"))
with col2:
    Sex = st.selectbox("Gender",("Male","Female"))
with col3:
    Age = st.number_input("Age of passenger")


col4,col5 = st.columns(2)

with col4:
    SibSp = st.number_input("Siblings/Spouses")
with col5:
    Parch = st.number_input("Parents/Children")

col7,col8 = st.columns(2)
with col7:
    Fare = st.number_input("Fare of Journey")
with col8:
    Embarked = st.selectbox("Picking Point",("Cherbourg","Queenstown","Southampton"))

if st.button("Predict"):
    pclass = 1
    if Pclass=="Economy":
        pclass = 3
    elif Pclass=="Executive":
        pclass = 2

    gender = 0
    if Sex=="Female":
        gender=1

    age = math.ceil(Age)
    sibsp = math.ceil(SibSp)
    parch = math.ceil(Parch)
    fare = math.ceil(Fare)

    embarked = 0
    if Embarked=="Cherbourg":
        embarked = 1
    elif Embarked=="Queenstown":
        embarked = 2

    result = model.predict([[pclass,gender,age,sibsp,parch,fare,embarked]])
    output_labels = {1: "The passenger will Survive",
                     0: "The passenger will not survive"}
    st.markdown(f"## {output_labels[result[0]]}")